spring:
  application:
    name: comment_services
  datasource:
    url: jdbc:h2:mem:kafka
  kafka:
    bootstrap-servers: ${HOST_IP_ADDRESS:localhost}:9092,${HOST_IP_ADDRESS:localhost}:9093,${HOST_IP_ADDRESS:localhost}:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: org.travel-blog
      auto-offset-reset: earliest
  ##0: no wait for kafka response
  ##1: leader write success, not wait for follower
  ##-1: wait for all leader, and replication
server:
  port: 8090
  servlet:
    context-path: /